name             'aws-base'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures aws-base'
long_description 'Installs/Configures aws-base'
version          '0.1.1'
